version: '3.4'
services: 
    web:
        build:
          context: .
          dockerfile: Dockerfile.dev
          network: host          
        ports:
          - "3000:3000" 
        volumes:
          - /app/node_modules
          - .:/app
        stdin_open: true
